/* acconfig.h.  Generated by Frank Hoeppner */

@TOP@

/* Standard Template Library (STL) was found on this system (presupposed) */
#undef STL_FOUND

/* STL contains stl_config.h */
#undef BOOL_DEFINED_IN_STL_CONFIG_H

/* STL contains bool.h */
#undef BOOL_DEFINED_IN_BOOL_H

/* Some compilers have problems with template<> */
#undef TEMPLATE_SPECIALIZATION

/* OpenGL capabilities available */
#undef OPENGL

/* Log/Trace debugging available */
#undef LOGTRACE_DEBUG

/* Log/Trace debugging turned off, but abort when error occurs */
#undef LOGTRACE_ERRMSG

@BOTTOM@

/* we use Namespaces */
#define USE_NAMESPACES

/* With Microsoft VC we need no explicit template instantiation */
#ifdef _MSC_VER
#  define NO_EXPLICIT_TEMPLATE_INSTANTIATION
#endif
