
# convert data.tab to all supported file format and compare against itself
# Frank Hoeppner, 2002 July 5

echo "testing file format conversion"

# test no 1

../../src/copy "data:f<data.tab>x.csv"
../../src/copy "data:f<x.csv>y.ddl"
../../src/copy "data:f<y.ddl>z.tab"
diff --ignore-all-space --ignore-blank-lines z.tab data.tab

# test no 2 (fields of varying size)

../../src/copy "data:f<data.csv>y.ddl data/label:c"
diff --ignore-all-space --ignore-blank-lines data.ddl y.ddl



