<data><value 0><t 0></data>
<data><value 1><t 1></data>
<data><value 2><t 2></data>
<data><value 3><t 3></data>
<data><value 4><t 4></data>
<data><value 5><t 5></data>
<data><value 6><t 6></data>
<data><value 7><t 7></data>
<data><value 8><t 8></data>
<data><value 9><t 9></data>
